apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-service-monitor
  labels:
    app: {{ .Chart.Name }}
spec:
  endpoints:
  - path: /metrics
    port: {{ .Values.service.portname }} # port name from the service file
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: {{ .Chart.Name }}

# reset the config with
# curl -s -XPOST localhost:9090/-/reload -v
# takes about a minute 