apiVersion: v1
kind: Service
metadata:
  name: axa
  labels:
    app: {{ .Chart.Name }}
    prometheus: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portname }}
      port: {{ .Values.service.internalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}